;Parsnp configuration File
;
[Reference]
file=/home/Users/rdd4/bronko_test/alignment_comparisons/hiv_evolution_results/S3/parsnp_100_consensus/ancestral_sequence.fa.ref
reverse=0
[Query]
file1=consensus_sequences/50-83-0.062133.fasta
reverse1=0
file2=consensus_sequences/68-27-0.141118.fasta
reverse2=0
file3=consensus_sequences/14-56-0.046590.fasta
reverse3=0
file4=consensus_sequences/28-30-0.432022.fasta
reverse4=0
file5=consensus_sequences/26-55-0.451799.fasta
reverse5=0
file6=consensus_sequences/72-98-0.242475.fasta
reverse6=0
file7=consensus_sequences/6-57-0.351311.fasta
reverse7=0
file8=consensus_sequences/62-48-0.296761.fasta
reverse8=0
file9=consensus_sequences/64-8-0.029273.fasta
reverse9=0
file10=consensus_sequences/48-50-0.031841.fasta
reverse10=0
file11=consensus_sequences/56-49-0.256628.fasta
reverse11=0
file12=consensus_sequences/46-43-0.202098.fasta
reverse12=0
file13=consensus_sequences/30-70-0.261161.fasta
reverse13=0
file14=consensus_sequences/16-11-0.108007.fasta
reverse14=0
file15=consensus_sequences/24-41-0.253877.fasta
reverse15=0
file16=consensus_sequences/70-88-0.403171.fasta
reverse16=0
file17=consensus_sequences/52-91-0.290508.fasta
reverse17=0
file18=consensus_sequences/60-36-0.213448.fasta
reverse18=0
file19=consensus_sequences/44-31-0.159809.fasta
reverse19=0
file20=consensus_sequences/54-96-0.220146.fasta
reverse20=0
file21=consensus_sequences/74-3-0.458640.fasta
reverse21=0
file22=consensus_sequences/58-68-0.341532.fasta
reverse22=0
file23=consensus_sequences/42-59-0.104116.fasta
reverse23=0
file24=consensus_sequences/38-37-0.022718.fasta
reverse24=0
file25=consensus_sequences/8-4-0.233787.fasta
reverse25=0
file26=consensus_sequences/66-89-0.102048.fasta
reverse26=0
file27=consensus_sequences/12-66-0.270719.fasta
reverse27=0
file28=consensus_sequences/0-42-0.284972.fasta
reverse28=0
file29=consensus_sequences/76-17-0.002690.fasta
reverse29=0
file30=consensus_sequences/32-99-0.358423.fasta
reverse30=0
file31=consensus_sequences/40-34-0.239630.fasta
reverse31=0
file32=consensus_sequences/18-82-0.208535.fasta
reverse32=0
file33=consensus_sequences/2-16-0.175737.fasta
reverse33=0
file34=consensus_sequences/22-76-0.026383.fasta
reverse34=0
file35=consensus_sequences/34-73-0.018221.fasta
reverse35=0
file36=consensus_sequences/36-93-0.030735.fasta
reverse36=0
file37=consensus_sequences/4-20-0.054944.fasta
reverse37=0
file38=consensus_sequences/10-90-0.039065.fasta
reverse38=0
file39=consensus_sequences/20-86-0.311521.fasta
reverse39=0
[MUM]
anchors=1.1*(Log(S))
anchorfile=
anchorsonly=0
calcmumi=0
mums=1.1*(Log(S))
mumfile=
filter=1
factor=2.0
extendmums=0
[LCB]
recombfilter=0
cores=1
diagdiff=0.12
doalign=2
c=21
d=300
q=30
p=15000000
icr=0
unaligned=0
[Output]
outdir=/home/Users/rdd4/bronko_test/alignment_comparisons/hiv_evolution_results/S3/parsnp_100_consensus
prefix=parsnp
showbps=1

