;Parsnp configuration File
;
[Reference]
file=/home/Users/rdd4/bronko_test/alignment_comparisons/hiv_evolution_results/parsnp_100/ancestral_sequence.fa.ref
reverse=0
[Query]
file1=individual_sequences/60-70-2.504461.fasta
reverse1=0
file2=individual_sequences/50-36-3.243392.fasta
reverse2=0
file3=individual_sequences/52-58-2.996754.fasta
reverse3=0
file4=individual_sequences/26-11-8.569515.fasta
reverse4=0
file5=individual_sequences/46-93-3.956141.fasta
reverse5=0
file6=individual_sequences/24-17-6.861790.fasta
reverse6=0
file7=individual_sequences/62-7-2.889471.fasta
reverse7=0
file8=individual_sequences/78-12-0.650831.fasta
reverse8=0
file9=individual_sequences/30-89-6.198196.fasta
reverse9=0
file10=individual_sequences/14-63-7.563975.fasta
reverse10=0
file11=individual_sequences/72-61-3.054555.fasta
reverse11=0
file12=individual_sequences/16-33-8.924685.fasta
reverse12=0
file13=individual_sequences/84-21-1.840363.fasta
reverse13=0
file14=individual_sequences/56-22-3.002112.fasta
reverse14=0
file15=individual_sequences/28-13-6.434056.fasta
reverse15=0
file16=individual_sequences/68-90-1.869360.fasta
reverse16=0
file17=individual_sequences/6-2-8.939474.fasta
reverse17=0
file18=individual_sequences/93-1-0.164434.fasta
reverse18=0
file19=individual_sequences/40-35-5.565499.fasta
reverse19=0
file20=individual_sequences/64-59-3.216893.fasta
reverse20=0
file21=individual_sequences/91-0-1.053508.fasta
reverse21=0
file22=individual_sequences/66-62-2.236102.fasta
reverse22=0
file23=individual_sequences/74-54-1.203181.fasta
reverse23=0
file24=individual_sequences/54-86-2.716507.fasta
reverse24=0
file25=individual_sequences/44-72-4.159113.fasta
reverse25=0
file26=individual_sequences/48-94-3.304975.fasta
reverse26=0
file27=individual_sequences/8-52-8.816802.fasta
reverse27=0
file28=individual_sequences/86-6-3.248080.fasta
reverse28=0
file29=individual_sequences/0-27-9.671371.fasta
reverse29=0
file30=individual_sequences/42-26-6.333234.fasta
reverse30=0
file31=individual_sequences/38-18-4.544806.fasta
reverse31=0
file32=individual_sequences/82-80-1.238099.fasta
reverse32=0
file33=individual_sequences/32-98-6.222170.fasta
reverse33=0
file34=individual_sequences/76-79-1.037730.fasta
reverse34=0
file35=individual_sequences/88-5-3.218629.fasta
reverse35=0
file36=individual_sequences/12-92-9.492387.fasta
reverse36=0
file37=individual_sequences/58-84-2.977225.fasta
reverse37=0
file38=individual_sequences/18-32-8.151437.fasta
reverse38=0
file39=individual_sequences/70-10-2.423773.fasta
reverse39=0
file40=individual_sequences/2-76-9.245086.fasta
reverse40=0
file41=individual_sequences/22-78-8.048727.fasta
reverse41=0
file42=individual_sequences/34-57-6.264782.fasta
reverse42=0
file43=individual_sequences/36-28-5.359203.fasta
reverse43=0
file44=individual_sequences/4-83-9.464083.fasta
reverse44=0
file45=individual_sequences/10-50-8.872630.fasta
reverse45=0
file46=individual_sequences/20-38-7.951598.fasta
reverse46=0
file47=individual_sequences/80-60-1.066224.fasta
reverse47=0
[MUM]
anchors=1.1*(Log(S))
anchorfile=
anchorsonly=0
calcmumi=0
mums=1.1*(Log(S))
mumfile=
filter=1
factor=2.0
extendmums=0
[LCB]
recombfilter=0
cores=1
diagdiff=0.12
doalign=2
c=21
d=300
q=30
p=15000000
icr=0
unaligned=0
[Output]
outdir=/home/Users/rdd4/bronko_test/alignment_comparisons/hiv_evolution_results/parsnp_100/
prefix=parsnp
showbps=1

