;Parsnp configuration File
;
[Reference]
file=/home/Users/rdd4/bronko_test/alignment_comparisons/hiv_evolution_results/parsnp_100/ancestral_sequence.fa.ref
reverse=0
[Query]
file1=individual_sequences/0-23-0.098532.fasta
reverse1=0
file2=individual_sequences/10-83-0.076895.fasta
reverse2=0
file3=individual_sequences/12-9-0.345404.fasta
reverse3=0
file4=individual_sequences/14-53-0.427146.fasta
reverse4=0
file5=individual_sequences/16-90-0.499308.fasta
reverse5=0
file6=individual_sequences/18-30-0.060340.fasta
reverse6=0
file7=individual_sequences/20-0-0.306216.fasta
reverse7=0
file8=individual_sequences/22-48-0.304350.fasta
reverse8=0
file9=individual_sequences/24-10-0.056004.fasta
reverse9=0
file10=individual_sequences/2-52-0.362219.fasta
reverse10=0
file11=individual_sequences/26-82-0.187728.fasta
reverse11=0
file12=individual_sequences/28-5-0.191505.fasta
reverse12=0
file13=individual_sequences/30-62-0.206087.fasta
reverse13=0
file14=individual_sequences/32-77-0.273127.fasta
reverse14=0
file15=individual_sequences/34-73-0.334718.fasta
reverse15=0
file16=individual_sequences/36-97-0.371712.fasta
reverse16=0
file17=individual_sequences/38-12-0.232429.fasta
reverse17=0
file18=individual_sequences/40-57-0.343879.fasta
reverse18=0
file19=individual_sequences/4-25-0.459532.fasta
reverse19=0
file20=individual_sequences/42-7-0.015329.fasta
reverse20=0
file21=individual_sequences/44-89-0.015900.fasta
reverse21=0
file22=individual_sequences/46-4-0.031722.fasta
reverse22=0
file23=individual_sequences/48-79-0.278710.fasta
reverse23=0
file24=individual_sequences/50-70-0.309395.fasta
reverse24=0
file25=individual_sequences/52-37-0.259740.fasta
reverse25=0
file26=individual_sequences/54-16-0.210629.fasta
reverse26=0
file27=individual_sequences/56-61-0.198293.fasta
reverse27=0
file28=individual_sequences/58-54-0.413551.fasta
reverse28=0
file29=individual_sequences/60-78-0.305355.fasta
reverse29=0
file30=individual_sequences/6-11-0.092686.fasta
reverse30=0
file31=individual_sequences/62-88-0.463081.fasta
reverse31=0
file32=individual_sequences/64-65-0.413309.fasta
reverse32=0
file33=individual_sequences/66-33-0.355178.fasta
reverse33=0
file34=individual_sequences/68-66-0.019926.fasta
reverse34=0
file35=individual_sequences/70-28-0.297632.fasta
reverse35=0
file36=individual_sequences/72-67-0.016729.fasta
reverse36=0
file37=individual_sequences/74-98-0.056818.fasta
reverse37=0
file38=individual_sequences/76-55-0.131487.fasta
reverse38=0
file39=individual_sequences/78-1-0.289326.fasta
reverse39=0
file40=individual_sequences/80-3-0.454627.fasta
reverse40=0
file41=individual_sequences/8-99-0.089017.fasta
reverse41=0
[MUM]
anchors=1.1*(Log(S))
anchorfile=
anchorsonly=0
calcmumi=1
mums=1.1*(Log(S))
mumfile=
filter=1
factor=2.0
extendmums=0
[LCB]
recombfilter=0
cores=1
diagdiff=0.12
doalign=2
c=21
d=300
q=30
p=15000000
icr=0
unaligned=$UNALIGNED
[Output]
outdir=/home/Users/rdd4/bronko_test/alignment_comparisons/hiv_evolution_results/parsnp_100/
prefix=parsnp
showbps=1

