;Parsnp configuration File
;
[Reference]
file=../../../bronko_test/sars_evolution_results/parsnp_consensus/ancestral_sequence.fa.ref
reverse=0
[Query]
file1=1067-6768-0.116656.fasta
reverse1=0
file2=1373-6524-0.105837.fasta
reverse2=0
[MUM]
anchors=1.1*(Log(S))
anchorfile=
anchorsonly=0
calcmumi=0
mums=1.1*(Log(S))
mumfile=
filter=1
factor=2.0
extendmums=0
[LCB]
recombfilter=0
cores=2
diagdiff=0.12
doalign=2
c=21
d=300
q=30
p=15000000
icr=0
unaligned=0
[Output]
outdir=../../../bronko_test/sars_evolution_results/parsnp_consensus/partition/chunk-0000000011-out
prefix=parsnp
showbps=1

