;Parsnp configuration File
;
[Reference]
file=/home/Users/rdd4/bronko_test/alignment_comparisons/hiv_evolution_results/parsnp_100_base_sequences3/ancestral_sequence.fa.ref
reverse=0
[Query]
file1=consensus_sequences/0-2-0.189533.fasta
reverse1=0
file2=consensus_sequences/10-15-0.185358.fasta
reverse2=0
file3=consensus_sequences/12-34-0.325192.fasta
reverse3=0
file4=consensus_sequences/14-48-0.410520.fasta
reverse4=0
file5=consensus_sequences/16-6-0.396032.fasta
reverse5=0
file6=consensus_sequences/18-18-0.156890.fasta
reverse6=0
file7=consensus_sequences/20-31-0.225142.fasta
reverse7=0
file8=consensus_sequences/22-91-0.348475.fasta
reverse8=0
file9=consensus_sequences/24-68-0.272818.fasta
reverse9=0
file10=consensus_sequences/2-53-0.380368.fasta
reverse10=0
file11=consensus_sequences/26-11-0.161928.fasta
reverse11=0
file12=consensus_sequences/28-52-0.191228.fasta
reverse12=0
file13=consensus_sequences/30-46-0.092426.fasta
reverse13=0
file14=consensus_sequences/32-62-0.077237.fasta
reverse14=0
file15=consensus_sequences/34-92-0.190368.fasta
reverse15=0
file16=consensus_sequences/36-74-0.276772.fasta
reverse16=0
file17=consensus_sequences/38-7-0.430798.fasta
reverse17=0
file18=consensus_sequences/40-51-0.040598.fasta
reverse18=0
file19=consensus_sequences/42-37-0.338952.fasta
reverse19=0
file20=consensus_sequences/44-38-0.325374.fasta
reverse20=0
file21=consensus_sequences/4-63-0.277289.fasta
reverse21=0
file22=consensus_sequences/46-54-0.035823.fasta
reverse22=0
file23=consensus_sequences/48-93-0.236361.fasta
reverse23=0
file24=consensus_sequences/50-64-0.389780.fasta
reverse24=0
file25=consensus_sequences/52-98-0.006603.fasta
reverse25=0
file26=consensus_sequences/54-27-0.410672.fasta
reverse26=0
file27=consensus_sequences/56-42-0.323257.fasta
reverse27=0
file28=consensus_sequences/58-69-0.368930.fasta
reverse28=0
file29=consensus_sequences/60-81-0.279477.fasta
reverse29=0
file30=consensus_sequences/62-70-0.407166.fasta
reverse30=0
file31=consensus_sequences/64-40-0.015648.fasta
reverse31=0
file32=consensus_sequences/6-45-0.495324.fasta
reverse32=0
file33=consensus_sequences/66-44-0.066319.fasta
reverse33=0
file34=consensus_sequences/68-60-0.452212.fasta
reverse34=0
file35=consensus_sequences/70-84-0.030962.fasta
reverse35=0
file36=consensus_sequences/72-77-0.425471.fasta
reverse36=0
file37=consensus_sequences/8-79-0.464173.fasta
reverse37=0
[MUM]
anchors=1.1*(Log(S))
anchorfile=
anchorsonly=0
calcmumi=1
mums=1.1*(Log(S))
mumfile=
filter=1
factor=2.0
extendmums=0
[LCB]
recombfilter=0
cores=1
diagdiff=0.12
doalign=2
c=21
d=300
q=30
p=15000000
icr=0
unaligned=$UNALIGNED
[Output]
outdir=/home/Users/rdd4/bronko_test/alignment_comparisons/hiv_evolution_results/parsnp_100_base_sequences3/
prefix=parsnp
showbps=1

